// import SpeakerStamp from '../components/SpeakerStamp'

export const speakersList = [
  {
    imageUrl: '/static/speakers/marc-andre',
    imageFormat: 'jpg',
    name: 'Marc-André Giroux',
    bio: 'Senior Platform Engineer, GitHub',
    twitter: '__xuorig__',
    github: 'xuorig',
  },
  {
    imageUrl: '/static/speakers/scott',
    imageFormat: 'jpg',
    name: 'Scott Walkinshaw',
    bio: 'Developer Lead, Shopify',
    twitter: 'swalkinshaw',
    github: 'swalkinshaw',
  },
  {
    imageUrl: '/static/speakers/chang',
    imageFormat: 'png',
    name: 'Chang Wang',
    bio: 'Platform Engineer, Apollo GraphQL',
    twitter: 'cheapsteak',
    github: 'cheapsteak',
  },
  {
    imageUrl: '/static/speakers/antoine',
    imageFormat: 'jpg',
    name: 'Antoine Genereux',
    bio: 'Solutions Architect, AWS Canada',
    twitter: 'antoinegenereux',
  },
  {
    imageUrl: '/static/speakers/jane',
    imageFormat: 'jpg',
    name: 'Jane Shen',
    bio: 'Cloud Application Architect, AWS Canada',
    twitter: 'j_shen',
  },
  {
    imageUrl: '/static/speakers/andrew',
    imageFormat: 'jpg',
    name: 'Andrew Kumar',
    bio: 'Head of Product Development, Digital Platforms, TELUS',
    twitter: 'kumar',
    github: 'andrewkumar',
  },
  {
    imageUrl: '/static/speakers/bill',
    imageFormat: 'jpg',
    name: 'Bill Li',
    bio: 'API Platform Developer, TELUS',
    twitter: 'billxinli',
    github: 'billxinli',
  },
  {
    imageUrl: '/static/speakers/leanne',
    imageFormat: 'jpg',
    name: 'Leanne Shapton',
    bio: 'Software Developer, Shopify',
    twitter: 'leeshapton',
    github: undefined,
  },
  {
    imageUrl: '/static/speakers/suresh',
    imageFormat: 'jpg',
    name: 'Suresh Subasinghe',
    bio: 'Director, Digital Platform Architecture, Air Canada',
    linkedin: 'ssubasinghe',
  },
  {
    imageUrl: '/static/speakers/erica',
    imageFormat: 'jpg',
    name: 'Erica Pisani',
    bio: 'Full Stack Engineer, BenchSci',
    twitter: 'ericapisani',
  },
  {
    imageUrl: '/static/speakers/ryan',
    imageFormat: 'jpg',
    name: 'Ryan Chenkie',
    bio:
      'Full Stack JavaScript Developer, Trainer, and Google Developer Expert',
    twitter: 'ryanchenkie',
    github: 'chenkie',
  },
  {
    imageUrl: '/static/speakers/raj',
    imageFormat: 'jpg',
    name: 'Raj Singh',
    bio: 'CEO & Co-founder, Novvum',
    twitter: 'RajInWonderland',
    github: 'RajInWonderland',
  },
  {
    imageUrl: '/static/speakers/rohit',
    imageFormat: 'jpg',
    name: 'Rohit Ravikoti',
    bio: 'CTO & Co-founder, Novvum',
    twitter: 'rovvum',
    github: 'rohit-ravikoti',
  },
]
